version: '3.4'
services:
    gitea-db:
      image: mariadb
      container_name: ${GITEA_MYSQL_HOST}
      restart: always
      env_file:
          - .env
      environment:
          - MYSQL_DATABASE=${GITEA_MYSQL_DATABASE}
          - MYSQL_ROOT_PASSWORD=${GITEA_MYSQL_ROOT_PASSWORD}
          - MYSQL_USER=${GITEA_MYSQL_USER}
          - MYSQL_PASSWORD=${GITEA_MYSQL_PASSWORD}
      volumes:
          - gitea-data:/var/lib/mysql
      networks:
          - my-network
    
    gitea-app:
      image: gitea/gitea
      container_name: gitea-app
      restart: always
      ports:
        - ${GITEA_SSH_PORT}:22
        - ${GITEA_HOST_PORT}:3000
      environment:
        - RUN_CROND=true
        - VIRTUAL_HOST=${GITEA_VIRTUAL_HOST}
        - VIRTUAL_PORT=3000
        - LETSENCRYPT_HOST=${GITEA_VIRTUAL_HOST}
        - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      volumes:
        - gitea-data:/data
      depends_on:
        - gitea-db

volumes:
  gitea-data:
    driver: local
    name: gitea-db

networks:
    my-network:
       external:
         name: nginx-proxy
